### PR TITLE
Update Dependecies ⭐

### PR DESCRIPTION
**Pull request by NiiightmareXD**
Updated Dependencies like [displayrecorder](https://github.com/robmikh/displayrecorder) 

Also, is there any way to handle GraphicsCaptureItem.Closed event in Rust? I tried to set up DispatcheQueue, but I Failed

### CODE REVIEW

**Comment by robmikh** [comment]
Thanks for the contribution! This looks great, although I have one request. Could you restore the launch.json file? I get that this breaks convention, but I hate having to copy and paste that file between projects every time I want to debug inside VS Code.

**Comment by robmikh** [comment]
Sorry, didn't notice your question. Could you open an issue about the failure when setting up a DispatcherQueue? The minesweeper-rs repo has an example of setting that up, and you also have to be pumping messages on that thread for the event to properly work.

**Comment by robmikh** [comment]
Thanks!

**Comment by NiiightmareXD** [comment]
No problem, The Dispatcher issue is fixed now and here is a screen capture library that I wrote with Graphics Capture API for Rust If you are interested [windows-capture](https://github.com/NiiightmareXD/windows-capture)

**Pull request merged**
